// Code generated by acp-go-generator; DO NOT EDIT.

package acp

// NewPlanUpdateContentItems constructs a PlanUpdateContent using the 'items' variant.
func NewPlanUpdateContentItems(planId PlanId, entries []PlanEntry) PlanUpdateContent {
	return PlanUpdateContent{Items: &PlanUpdateContentItems{
		Entries: entries,
		PlanId:  planId,
		Type:    "items",
	}}
}

// NewPlanUpdateContentFile constructs a PlanUpdateContent using the 'file' variant.
func NewPlanUpdateContentFile(planId PlanId, uri string) PlanUpdateContent {
	return PlanUpdateContent{File: &PlanUpdateContentFile{
		PlanId: planId,
		Type:   "file",
		Uri:    uri,
	}}
}

// NewPlanUpdateContentMarkdown constructs a PlanUpdateContent using the 'markdown' variant.
func NewPlanUpdateContentMarkdown(planId PlanId, content string) PlanUpdateContent {
	return PlanUpdateContent{Markdown: &PlanUpdateContentMarkdown{
		Content: content,
		PlanId:  planId,
		Type:    "markdown",
	}}
}

// NewRequestPermissionOutcomeCancelled constructs a RequestPermissionOutcome using the 'cancelled' variant.
func NewRequestPermissionOutcomeCancelled() RequestPermissionOutcome {
	return RequestPermissionOutcome{Cancelled: &RequestPermissionOutcomeCancelled{Outcome: "cancelled"}}
}

// NewRequestPermissionOutcomeSelected constructs a RequestPermissionOutcome using the 'selected' variant.
func NewRequestPermissionOutcomeSelected(optionId PermissionOptionId) RequestPermissionOutcome {
	return RequestPermissionOutcome{Selected: &RequestPermissionOutcomeSelected{
		OptionId: optionId,
		Outcome:  "selected",
	}}
}

// NewSessionConfigOptionSelect constructs a SessionConfigOption using the 'select' variant.
func NewSessionConfigOptionSelect(currentValue SessionConfigValueId, options SessionConfigSelectOptions) SessionConfigOption {
	return SessionConfigOption{Select: &SessionConfigOptionSelect{
		CurrentValue: currentValue,
		Options:      options,
		Type:         "select",
	}}
}

// NewSessionConfigOptionBoolean constructs a SessionConfigOption using the 'boolean' variant.
func NewSessionConfigOptionBoolean(currentValue bool) SessionConfigOption {
	return SessionConfigOption{Boolean: &SessionConfigOptionBoolean{
		CurrentValue: currentValue,
		Type:         "boolean",
	}}
}

// NewUnstableNesSuggestionEdit constructs a UnstableNesSuggestion using the 'edit' variant.
func NewUnstableNesSuggestionEdit(id UnstableNesSuggestionId, uri string, edits []UnstableNesTextEdit) UnstableNesSuggestion {
	return UnstableNesSuggestion{Edit: &UnstableNesSuggestionEdit{
		Edits: edits,
		Id:    id,
		Kind:  "edit",
		Uri:   uri,
	}}
}

// NewUnstableNesSuggestionJump constructs a UnstableNesSuggestion using the 'jump' variant.
func NewUnstableNesSuggestionJump(id UnstableNesSuggestionId, uri string, position UnstablePosition) UnstableNesSuggestion {
	return UnstableNesSuggestion{Jump: &UnstableNesSuggestionJump{
		Id:       id,
		Kind:     "jump",
		Position: position,
		Uri:      uri,
	}}
}

// NewUnstableNesSuggestionRename constructs a UnstableNesSuggestion using the 'rename' variant.
func NewUnstableNesSuggestionRename(id UnstableNesSuggestionId, uri string, position UnstablePosition, newName string) UnstableNesSuggestion {
	return UnstableNesSuggestion{Rename: &UnstableNesSuggestionRename{
		Id:       id,
		Kind:     "rename",
		NewName:  newName,
		Position: position,
		Uri:      uri,
	}}
}

// NewUnstableNesSuggestionSearchAndReplace constructs a UnstableNesSuggestion using the 'searchAndReplace' variant.
func NewUnstableNesSuggestionSearchAndReplace(id UnstableNesSuggestionId, uri string, search string, replace string) UnstableNesSuggestion {
	return UnstableNesSuggestion{SearchAndReplace: &UnstableNesSuggestionSearchAndReplace{
		Id:      id,
		Kind:    "searchAndReplace",
		Replace: replace,
		Search:  search,
		Uri:     uri,
	}}
}
